const required = [
  'DATABASE_URL',
  'BLOB_READ_WRITE_TOKEN',
  'APP_PASSWORD_HASH',
  'APP_SESSION_SECRET',
  'APP_ENCRYPTION_KEY'
];

const missing = required.filter(key => !process.env[key]);

if (missing.length > 0) {
  console.error(`Missing environment variables: ${missing.join(', ')}`);
  process.exit(1);
}

if (!process.env.APP_PASSWORD_HASH.startsWith('scrypt:')) {
  console.error('APP_PASSWORD_HASH must be generated by `npm run hash-password -- "password"`');
  process.exit(1);
}

if (process.env.APP_SESSION_SECRET.length < 32 || process.env.APP_ENCRYPTION_KEY.length < 32) {
  console.error('APP_SESSION_SECRET and APP_ENCRYPTION_KEY should be at least 32 characters');
  process.exit(1);
}

console.log('Environment looks ready for Vercel backend startup.');
